-- First scene seed data (auto-generated by save_first_scenes_to_seed.py)
-- Restores pre-generated opening scenes for all portrait × build combos
-- so gameplay starts instantly without waiting on Gemini/ElevenLabs.

DELETE FROM public.first_scenes WHERE portrait_id ~ '^[mf][1-4]$';

INSERT INTO public.first_scenes (
    portrait_id, build_type, narration, visual_scene,
    image_url, audio_url, choices, is_successful, retry_count
) VALUES (
    'f1',
    'mage',
    'A searing pain pulsed behind her eyes as she lay amongst splintered wood and overturned barrels, a dark pool of dry blood beneath her. (My head... it throbs. Everything''s blurry. Where am I? What happened?)',
    'A forest clearing, bathed in soft morning light. Shattered wooden barrels and scattered debris lie on the weathered ground, with a distinct, dark stain of dried blood.',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/scene_f1_mage.png',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/narration_f1_mage.mp3',
    '[{"id": "choice_1", "text": "Try to push herself up slowly and carefully survey the immediate surroundings."}, {"id": "choice_2", "text": "Fumble weakly for any items left on her person or nearby."}, {"id": "choice_3", "text": "Close her eyes and listen intently for any sounds or movement in the forest."}, {"id": "choice_4", "text": "Lie still for a moment, trying to force a single memory to surface."}]'::jsonb,
    TRUE,
    0
) ON CONFLICT (portrait_id, build_type) DO UPDATE SET
    narration = EXCLUDED.narration,
    visual_scene = EXCLUDED.visual_scene,
    image_url = EXCLUDED.image_url,
    audio_url = EXCLUDED.audio_url,
    choices = EXCLUDED.choices,
    is_successful = TRUE,
    retry_count = 0,
    last_error = NULL,
    generated_at = NOW();

INSERT INTO public.first_scenes (
    portrait_id, build_type, narration, visual_scene,
    image_url, audio_url, choices, is_successful, retry_count
) VALUES (
    'f1',
    'ranger',
    'A searing pain in her head, she stirred amidst splintered wood and overturned barrels, a dark stain of blood beneath her. (Where... what happened? My head... it throbs. I can''t see properly, everything''s a blur. Who am I?)',
    'A quiet forest clearing at dawn. Broken wooden barrels and scattered goods litter the weathered, dirt-stained ground. Sparse morning light filters through ancient tree canopies, revealing dried blood patches.',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/scene_f1_ranger.png',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/narration_f1_ranger.mp3',
    '[{"id": "choice_1", "text": "Try to stand up slowly and assess the immediate area."}, {"id": "choice_2", "text": "Pat my pockets and belt, hoping to find any familiar items."}, {"id": "choice_3", "text": "Close my eyes and try to recall anything from before this moment."}, {"id": "choice_4", "text": "Listen intently for any movement or voices in the trees."}]'::jsonb,
    TRUE,
    0
) ON CONFLICT (portrait_id, build_type) DO UPDATE SET
    narration = EXCLUDED.narration,
    visual_scene = EXCLUDED.visual_scene,
    image_url = EXCLUDED.image_url,
    audio_url = EXCLUDED.audio_url,
    choices = EXCLUDED.choices,
    is_successful = TRUE,
    retry_count = 0,
    last_error = NULL,
    generated_at = NOW();

INSERT INTO public.first_scenes (
    portrait_id, build_type, narration, visual_scene,
    image_url, audio_url, choices, is_successful, retry_count
) VALUES (
    'f1',
    'rogue',
    'A throbbing pain splits her skull as she stirs amidst shattered wood and spilled dirt, a dry blood pool beneath her cheek. (Where... where am I? My head screams. I can''t recall anything, not even my name.)',
    'A quiet forest clearing bathed in soft morning light. Broken wooden barrels and scattered debris lie on the weathered ground. Dry blood stains the dirt, hinting at a struggle. Overgrown roots twist through fallen leaves, adding to the desolate scene.',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/scene_f1_rogue.png',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/narration_f1_rogue.mp3',
    '[{"id": "choice_1", "text": "Try to sit up slowly and assess the pain in my head."}, {"id": "choice_2", "text": "Carefully scan the immediate surroundings for any danger."}, {"id": "choice_3", "text": "Reach for what feels like a pouch to check for items."}, {"id": "choice_4", "text": "Close my eyes and focus, trying to recall even a single memory."}]'::jsonb,
    TRUE,
    0
) ON CONFLICT (portrait_id, build_type) DO UPDATE SET
    narration = EXCLUDED.narration,
    visual_scene = EXCLUDED.visual_scene,
    image_url = EXCLUDED.image_url,
    audio_url = EXCLUDED.audio_url,
    choices = EXCLUDED.choices,
    is_successful = TRUE,
    retry_count = 0,
    last_error = NULL,
    generated_at = NOW();

INSERT INTO public.first_scenes (
    portrait_id, build_type, narration, visual_scene,
    image_url, audio_url, choices, is_successful, retry_count
) VALUES (
    'f1',
    'warrior',
    'She stirred, head throbbing savagely as blurry shapes resolved into broken wood and overturned barrels. A dark, dry stain clung to her cheek. (Where... am I? Everything hurts. I can''t remember. Who is this?)',
    'A quiet forest clearing, illuminated by dappled morning light. Splintered wood and ransacked, broken barrels litter the weathered, muddy ground, where patches of dry, dark blood stain the soil amidst scattered debris.',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/scene_f1_warrior.png',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/narration_f1_warrior.mp3',
    '[{"id": "choice_1", "text": "Try to push myself up slowly and look around"}, {"id": "choice_2", "text": "Pat myself down to check for any items I might still have"}, {"id": "choice_3", "text": "Close my eyes and listen intently for any nearby sounds"}, {"id": "choice_4", "text": "Lie still for a moment, trying to recall even a single memory"}]'::jsonb,
    TRUE,
    0
) ON CONFLICT (portrait_id, build_type) DO UPDATE SET
    narration = EXCLUDED.narration,
    visual_scene = EXCLUDED.visual_scene,
    image_url = EXCLUDED.image_url,
    audio_url = EXCLUDED.audio_url,
    choices = EXCLUDED.choices,
    is_successful = TRUE,
    retry_count = 0,
    last_error = NULL,
    generated_at = NOW();

INSERT INTO public.first_scenes (
    portrait_id, build_type, narration, visual_scene,
    image_url, audio_url, choices, is_successful, retry_count
) VALUES (
    'f2',
    'mage',
    'You stir amidst splintered wood and overturned barrels, a crimson stain beneath your head. Vision blurs. (What happened? This pain... I remember nothing. Who am I? I feel so weak, utterly disoriented.)',
    'A sun-dappled forest clearing reveals splintered wood, upturned, robbed barrels, and scattered debris across weathered, muddy ground. Morning light filters through the trees, casting long shadows over a dried bloodstain.',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/scene_f2_mage.png',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/narration_f2_mage.mp3',
    '[{"id": "choice_1", "text": "Try to sit up slowly and assess my immediate surroundings."}, {"id": "choice_2", "text": "Reach for my head, feeling for injuries and trying to stop the throbbing."}, {"id": "choice_3", "text": "Listen intently for any sounds that might indicate danger or movement nearby."}, {"id": "choice_4", "text": "Lie still for a moment, attempting to recall anything, even a name."}]'::jsonb,
    TRUE,
    0
) ON CONFLICT (portrait_id, build_type) DO UPDATE SET
    narration = EXCLUDED.narration,
    visual_scene = EXCLUDED.visual_scene,
    image_url = EXCLUDED.image_url,
    audio_url = EXCLUDED.audio_url,
    choices = EXCLUDED.choices,
    is_successful = TRUE,
    retry_count = 0,
    last_error = NULL,
    generated_at = NOW();

INSERT INTO public.first_scenes (
    portrait_id, build_type, narration, visual_scene,
    image_url, audio_url, choices, is_successful, retry_count
) VALUES (
    'f2',
    'ranger',
    'The ranger lies amidst splintered wood and overturned barrels, a dark stain near her head. Her vision blurs, the world spinning. (My head throbs. What happened? Who... who am I? I feel so terribly weak.)',
    'A quiet forest clearing at dawn, sunlight dappling through dense leaves onto the weathered ground. Broken wooden barrels and scattered debris, along with a dark pool of dry blood, mark the scene of a recent struggle.',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/scene_f2_ranger.png',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/narration_f2_ranger.mp3',
    '[{"id": "choice_1", "text": "Try to push myself up slowly and scan the immediate area."}, {"id": "choice_2", "text": "Pat myself down, checking for any remaining items or obvious injuries."}, {"id": "choice_3", "text": "Listen intently for any sounds that might indicate danger or another presence."}, {"id": "choice_4", "text": "Close my eyes for a moment, trying to recall anything from before this pain."}]'::jsonb,
    TRUE,
    0
) ON CONFLICT (portrait_id, build_type) DO UPDATE SET
    narration = EXCLUDED.narration,
    visual_scene = EXCLUDED.visual_scene,
    image_url = EXCLUDED.image_url,
    audio_url = EXCLUDED.audio_url,
    choices = EXCLUDED.choices,
    is_successful = TRUE,
    retry_count = 0,
    last_error = NULL,
    generated_at = NOW();

INSERT INTO public.first_scenes (
    portrait_id, build_type, narration, visual_scene,
    image_url, audio_url, choices, is_successful, retry_count
) VALUES (
    'f2',
    'rogue',
    'A cold, damp earth pressed against her, amidst splintered wood and broken barrels, a dark stain of dried blood beneath her. (My head... it throbs, vision swims. What happened? Who am I? Everything''s a blur, and I feel so weak.)',
    'A sun-dappled forest clearing, littered with splintered wooden barrels and scattered debris. Morning light filters through the canopy, illuminating the weathered, blood-stained earth.',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/scene_f2_rogue.png',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/narration_f2_rogue.mp3',
    '[{"id": "choice_1", "text": "Try to stand up slowly, bracing for pain, and look around."}, {"id": "choice_2", "text": "Frantically pat down my body, checking for any remaining items or weapons."}, {"id": "choice_3", "text": "Close my eyes and try to listen for any sounds of danger or movement nearby."}, {"id": "choice_4", "text": "Lie still for a moment, pressing my hands to my head, and attempt to recall anything at all."}]'::jsonb,
    TRUE,
    0
) ON CONFLICT (portrait_id, build_type) DO UPDATE SET
    narration = EXCLUDED.narration,
    visual_scene = EXCLUDED.visual_scene,
    image_url = EXCLUDED.image_url,
    audio_url = EXCLUDED.audio_url,
    choices = EXCLUDED.choices,
    is_successful = TRUE,
    retry_count = 0,
    last_error = NULL,
    generated_at = NOW();

INSERT INTO public.first_scenes (
    portrait_id, build_type, narration, visual_scene,
    image_url, audio_url, choices, is_successful, retry_count
) VALUES (
    'f2',
    'warrior',
    'The warrior lies amidst shattered wood and upturned barrels, a metallic scent of dry blood in the air. Her head throbs violently. (Where am I? My vision swims. I can''t remember anything, not even my name. What happened here?)',
    'A quiet forest clearing bathed in soft morning light. Broken wooden barrels and scattered debris lie across weathered, muddy ground. Dark, dry blood stains the disturbed earth.',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/scene_f2_warrior.png',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/narration_f2_warrior.mp3',
    '[{"id": "choice_1", "text": "Try to push myself up slowly and look around."}, {"id": "choice_2", "text": "Check my body and what I''m wearing for injuries or remaining items."}, {"id": "choice_3", "text": "Strain my ears, listening carefully for any sounds or movement nearby."}, {"id": "choice_4", "text": "Close my eyes and try to force a memory to surface."}]'::jsonb,
    TRUE,
    0
) ON CONFLICT (portrait_id, build_type) DO UPDATE SET
    narration = EXCLUDED.narration,
    visual_scene = EXCLUDED.visual_scene,
    image_url = EXCLUDED.image_url,
    audio_url = EXCLUDED.audio_url,
    choices = EXCLUDED.choices,
    is_successful = TRUE,
    retry_count = 0,
    last_error = NULL,
    generated_at = NOW();

INSERT INTO public.first_scenes (
    portrait_id, build_type, narration, visual_scene,
    image_url, audio_url, choices, is_successful, retry_count
) VALUES (
    'f3',
    'mage',
    'A throbbing pain pulsed behind her eyes as the forest floor swam into view. Broken barrels and splintered wood lay around, stained with a dark, unfamiliar dryness. (Where am I? Everything hurts, my mind is a fog. I feel so weak, so lost.)',
    'Morning light filters through a canopy of dark leaves into a small forest clearing. Broken wooden barrels and scattered debris litter the weathered, damp earth, amidst faded bloodstains. A dense woodland surrounds the scene.',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/scene_f3_mage.png',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/narration_f3_mage.mp3',
    '[{"id": "choice_1", "text": "Try to stand up slowly and look around"}, {"id": "choice_2", "text": "Check my belongings to see what''s left"}, {"id": "choice_3", "text": "Listen carefully for any sounds or threats"}, {"id": "choice_4", "text": "Rest a moment and try to remember something"}]'::jsonb,
    TRUE,
    0
) ON CONFLICT (portrait_id, build_type) DO UPDATE SET
    narration = EXCLUDED.narration,
    visual_scene = EXCLUDED.visual_scene,
    image_url = EXCLUDED.image_url,
    audio_url = EXCLUDED.audio_url,
    choices = EXCLUDED.choices,
    is_successful = TRUE,
    retry_count = 0,
    last_error = NULL,
    generated_at = NOW();

INSERT INTO public.first_scenes (
    portrait_id, build_type, narration, visual_scene,
    image_url, audio_url, choices, is_successful, retry_count
) VALUES (
    'f3',
    'ranger',
    'A dull ache throbs behind the ranger''s eyes as she lies amidst splintered wood and overturned barrels, a pool of dry blood staining the dirt. (Where am I? My head screams. Nothing makes sense, my memory''s a blank.)',
    'A quiet forest clearing bathed in soft morning light. Broken wooden barrels and scattered debris litter the weathered ground, hinting at a recent struggle. Patches of dried blood stain the soil.',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/scene_f3_ranger.png',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/narration_f3_ranger.mp3',
    '[{"id": "choice_1", "text": "Try to sit up slowly, pushing through the dizziness."}, {"id": "choice_2", "text": "Scan the immediate surroundings for any movement or lingering threats."}, {"id": "choice_3", "text": "Carefully pat my body, checking for any remaining belongings."}, {"id": "choice_4", "text": "Close my eyes and focus, trying to recall even a single detail of my past."}]'::jsonb,
    TRUE,
    0
) ON CONFLICT (portrait_id, build_type) DO UPDATE SET
    narration = EXCLUDED.narration,
    visual_scene = EXCLUDED.visual_scene,
    image_url = EXCLUDED.image_url,
    audio_url = EXCLUDED.audio_url,
    choices = EXCLUDED.choices,
    is_successful = TRUE,
    retry_count = 0,
    last_error = NULL,
    generated_at = NOW();

INSERT INTO public.first_scenes (
    portrait_id, build_type, narration, visual_scene,
    image_url, audio_url, choices, is_successful, retry_count
) VALUES (
    'f3',
    'rogue',
    'A throbbing ache splits her head as she lies amidst broken wood and spilled goods, a dull red pool nearby. (Where... am I? Everything blurs. I don''t remember this place. Who am I?)',
    'A small forest clearing, littered with splintered barrels and torn fabric. Faint morning light filters through ancient trees, illuminating dried bloodstains on the worn earth.',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/scene_f3_rogue.png',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/narration_f3_rogue.mp3',
    '[{"id": "choice_1", "text": "Try to push up slowly, leaning on something nearby."}, {"id": "choice_2", "text": "Check pockets and pouches for any remaining items."}, {"id": "choice_3", "text": "Listen for any sounds of movement or voices in the trees."}, {"id": "choice_4", "text": "Close my eyes for a moment, trying to recall anything at all."}]'::jsonb,
    TRUE,
    0
) ON CONFLICT (portrait_id, build_type) DO UPDATE SET
    narration = EXCLUDED.narration,
    visual_scene = EXCLUDED.visual_scene,
    image_url = EXCLUDED.image_url,
    audio_url = EXCLUDED.audio_url,
    choices = EXCLUDED.choices,
    is_successful = TRUE,
    retry_count = 0,
    last_error = NULL,
    generated_at = NOW();

INSERT INTO public.first_scenes (
    portrait_id, build_type, narration, visual_scene,
    image_url, audio_url, choices, is_successful, retry_count
) VALUES (
    'f3',
    'warrior',
    'She lay slumped amidst splintered wood and broken barrels, a pool of dry blood beneath her. (My head throbs, vision swimming. Where... where am I? I can''t remember anything, not even my name.)',
    'A dim forest clearing at dawn. Broken wooden barrels and scattered debris litter the weathered ground, stained with dry blood. Muted morning light filters through the trees.',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/scene_f3_warrior.png',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/narration_f3_warrior.mp3',
    '[{"id": "choice_1", "text": "Try to push myself up slowly and scan my immediate surroundings."}, {"id": "choice_2", "text": "Fumble for any remaining items on my person or nearby."}, {"id": "choice_3", "text": "Lie still and listen for any sounds of danger in the forest."}, {"id": "choice_4", "text": "Close my eyes for a moment, trying to recall anything... anything at all."}]'::jsonb,
    TRUE,
    0
) ON CONFLICT (portrait_id, build_type) DO UPDATE SET
    narration = EXCLUDED.narration,
    visual_scene = EXCLUDED.visual_scene,
    image_url = EXCLUDED.image_url,
    audio_url = EXCLUDED.audio_url,
    choices = EXCLUDED.choices,
    is_successful = TRUE,
    retry_count = 0,
    last_error = NULL,
    generated_at = NOW();

INSERT INTO public.first_scenes (
    portrait_id, build_type, narration, visual_scene,
    image_url, audio_url, choices, is_successful, retry_count
) VALUES (
    'f4',
    'mage',
    'The forest floor felt hard and cold beneath her, strewn with splintered wood and broken barrels near a dark, dry stain. (My head… it aches terribly. Where am I? My vision swims. I remember nothing.)',
    'A dim forest clearing at dawn, scattered with fragments of wooden barrels and other debris. Weathered, leaf-covered earth shows a dark, dry pool of blood, lit by dappled light.',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/scene_f4_mage.png',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/narration_f4_mage.mp3',
    '[{"id": "choice_1", "text": "Try to push up slowly and survey the immediate area."}, {"id": "choice_2", "text": "Pat down my clothes, checking for any remaining belongings."}, {"id": "choice_3", "text": "Listen intently for any distant sounds or signs of danger."}, {"id": "choice_4", "text": "Close my eyes for a moment, trying to recall *anything*."}]'::jsonb,
    TRUE,
    0
) ON CONFLICT (portrait_id, build_type) DO UPDATE SET
    narration = EXCLUDED.narration,
    visual_scene = EXCLUDED.visual_scene,
    image_url = EXCLUDED.image_url,
    audio_url = EXCLUDED.audio_url,
    choices = EXCLUDED.choices,
    is_successful = TRUE,
    retry_count = 0,
    last_error = NULL,
    generated_at = NOW();

INSERT INTO public.first_scenes (
    portrait_id, build_type, narration, visual_scene,
    image_url, audio_url, choices, is_successful, retry_count
) VALUES (
    'f4',
    'ranger',
    'The ranger stirs, head throbbing amidst broken wood and spilled contents. Dry blood cakes the ground around her, her vision swimming. (Where am I? Who am I? Everything hurts, a dense fog in my mind.)',
    'A sun-dappled forest clearing strewn with shattered barrels and splintered wood. Dry blood stains the weathered earth, catching the soft morning light filtering through the canopy. Debris lies scattered.',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/scene_f4_ranger.png',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/narration_f4_ranger.mp3',
    '[{"id": "choice_1", "text": "Try to push up slowly, leaning on something nearby."}, {"id": "choice_2", "text": "Pat down my clothes, checking for wounds or anything left on me."}, {"id": "choice_3", "text": "Strain to listen for any sounds beyond the forest''s natural hum."}, {"id": "choice_4", "text": "Close my eyes and try to force a memory, no matter how small."}]'::jsonb,
    TRUE,
    0
) ON CONFLICT (portrait_id, build_type) DO UPDATE SET
    narration = EXCLUDED.narration,
    visual_scene = EXCLUDED.visual_scene,
    image_url = EXCLUDED.image_url,
    audio_url = EXCLUDED.audio_url,
    choices = EXCLUDED.choices,
    is_successful = TRUE,
    retry_count = 0,
    last_error = NULL,
    generated_at = NOW();

INSERT INTO public.first_scenes (
    portrait_id, build_type, narration, visual_scene,
    image_url, audio_url, choices, is_successful, retry_count
) VALUES (
    'f4',
    'rogue',
    'The old woman stirs amidst splintered wood and scattered barrels, a pool of dry blood beneath her. (My head… it throbs so violently. Where am I? I can''t see properly, everything is a blur. Who am I?)',
    'A forest clearing at dawn, shattered wooden barrels and scattered supplies litter the weathered ground. Soft morning light filters through ancient trees, highlighting dried bloodstains near an unconscious figure.',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/scene_f4_rogue.png',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/narration_f4_rogue.mp3',
    '[{"id": "choice_1", "text": "Attempt to push up slowly, trying to clear my blurry vision."}, {"id": "choice_2", "text": "Weakly pat myself down, searching for any remaining possessions."}, {"id": "choice_3", "text": "Strain to listen for any sounds of movement in the dense woods."}, {"id": "choice_4", "text": "Close my eyes for a moment, trying desperately to remember something."}]'::jsonb,
    TRUE,
    0
) ON CONFLICT (portrait_id, build_type) DO UPDATE SET
    narration = EXCLUDED.narration,
    visual_scene = EXCLUDED.visual_scene,
    image_url = EXCLUDED.image_url,
    audio_url = EXCLUDED.audio_url,
    choices = EXCLUDED.choices,
    is_successful = TRUE,
    retry_count = 0,
    last_error = NULL,
    generated_at = NOW();

INSERT INTO public.first_scenes (
    portrait_id, build_type, narration, visual_scene,
    image_url, audio_url, choices, is_successful, retry_count
) VALUES (
    'f4',
    'warrior',
    'A weathered form lay crumpled among splintered wood and overturned barrels, a dark, dry pool beneath her head. (My vision swims... who am I? This pain... I remember nothing. What *is* this place?)',
    'A quiet forest clearing at dawn, dappled light filtering through tall trees. Broken wooden barrels and scattered goods litter the weathered, leaf-strewn ground. A dark, dry stain mars the earth.',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/scene_f4_warrior.png',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/narration_f4_warrior.mp3',
    '[{"id": "choice_1", "text": "(Try to push myself up slightly and squint at the blurry shapes around me.)"}, {"id": "choice_2", "text": "(Feel for anything on my person, even if my hands are shaky.)"}, {"id": "choice_3", "text": "(Focus my hearing, trying to catch any sound beyond my throbbing head.)"}, {"id": "choice_4", "text": "(Close my eyes for a moment, hoping a memory might surface from the fog.)"}]'::jsonb,
    TRUE,
    0
) ON CONFLICT (portrait_id, build_type) DO UPDATE SET
    narration = EXCLUDED.narration,
    visual_scene = EXCLUDED.visual_scene,
    image_url = EXCLUDED.image_url,
    audio_url = EXCLUDED.audio_url,
    choices = EXCLUDED.choices,
    is_successful = TRUE,
    retry_count = 0,
    last_error = NULL,
    generated_at = NOW();

INSERT INTO public.first_scenes (
    portrait_id, build_type, narration, visual_scene,
    image_url, audio_url, choices, is_successful, retry_count
) VALUES (
    'm1',
    'mage',
    'He lay amidst shattered wood and scattered barrels, a dull ache throbbing behind his eyes. (Who... am I? My head is screaming. I can''t see properly.) A faint smell of dry blood clung to the air. (What happened here? Everything''s a blur.)',
    'A quiet forest clearing. Shattered wooden barrels and debris are strewn across the weathered ground. Soft morning light filters through the tall trees, illuminating dry bloodstains and a lone, disoriented figure slowly stirring amidst the wreckage.',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/scene_m1_mage.png',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/narration_m1_mage.mp3',
    '[{"id": "choice_1", "text": "Try to push myself up slowly and look around."}, {"id": "choice_2", "text": "Check my body and tattered clothes for any remaining items."}, {"id": "choice_3", "text": "Listen carefully for any sounds or movement in the forest."}, {"id": "choice_4", "text": "Lie still for a moment, trying to recall anything about myself."}]'::jsonb,
    TRUE,
    0
) ON CONFLICT (portrait_id, build_type) DO UPDATE SET
    narration = EXCLUDED.narration,
    visual_scene = EXCLUDED.visual_scene,
    image_url = EXCLUDED.image_url,
    audio_url = EXCLUDED.audio_url,
    choices = EXCLUDED.choices,
    is_successful = TRUE,
    retry_count = 0,
    last_error = NULL,
    generated_at = NOW();

INSERT INTO public.first_scenes (
    portrait_id, build_type, narration, visual_scene,
    image_url, audio_url, choices, is_successful, retry_count
) VALUES (
    'm1',
    'ranger',
    'A dull ache throbbed in my skull. I lay amidst splintered wood and scattered barrels, a dried crimson pool beneath me. My vision blurred, trying to focus. (Where am I? My head is splitting. I can''t remember anything at all. What happened to me?)',
    'A dim forest clearing at dawn, dappled light filtering through the canopy. Broken wooden barrels and other debris are strewn across the weathered, blood-stained ground. The air is still and cool.',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/scene_m1_ranger.png',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/narration_m1_ranger.mp3',
    '[{"id": "choice_1", "text": "Try to push myself up slowly, just to see what''s around me."}, {"id": "choice_2", "text": "Check my body for any obvious injuries or what might be left in my pockets."}, {"id": "choice_3", "text": "Listen intently for any sounds, any sign of danger or other living beings nearby."}, {"id": "choice_4", "text": "Close my eyes and try to force a memory, any flicker of who I am or how I got here."}]'::jsonb,
    TRUE,
    0
) ON CONFLICT (portrait_id, build_type) DO UPDATE SET
    narration = EXCLUDED.narration,
    visual_scene = EXCLUDED.visual_scene,
    image_url = EXCLUDED.image_url,
    audio_url = EXCLUDED.audio_url,
    choices = EXCLUDED.choices,
    is_successful = TRUE,
    retry_count = 0,
    last_error = NULL,
    generated_at = NOW();

INSERT INTO public.first_scenes (
    portrait_id, build_type, narration, visual_scene,
    image_url, audio_url, choices, is_successful, retry_count
) VALUES (
    'm1',
    'rogue',
    'The forest floor felt hard and cold beneath him, splinters of wood and broken barrels scattered nearby, a pool of dry blood sticky on his clothes. His head throbbed, vision blurring. (What happened? Who am I? Everything is so unclear, so painful.)',
    'A quiet forest clearing at dawn. Broken wooden barrels and scattered debris litter the weathered ground. Soft morning light filters through the tree canopy, illuminating a dried, dark stain on the earth.',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/scene_m1_rogue.png',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/narration_m1_rogue.mp3',
    '[{"id": "choice_1", "text": "Try to push himself upright and survey the immediate area."}, {"id": "choice_2", "text": "Fumble for his pockets, checking for any remaining items."}, {"id": "choice_3", "text": "Lie still and listen intently for any sounds or movement in the forest."}, {"id": "choice_4", "text": "Close his eyes for a moment, trying to recall even a single memory."}]'::jsonb,
    TRUE,
    0
) ON CONFLICT (portrait_id, build_type) DO UPDATE SET
    narration = EXCLUDED.narration,
    visual_scene = EXCLUDED.visual_scene,
    image_url = EXCLUDED.image_url,
    audio_url = EXCLUDED.audio_url,
    choices = EXCLUDED.choices,
    is_successful = TRUE,
    retry_count = 0,
    last_error = NULL,
    generated_at = NOW();

INSERT INTO public.first_scenes (
    portrait_id, build_type, narration, visual_scene,
    image_url, audio_url, choices, is_successful, retry_count
) VALUES (
    'm1',
    'warrior',
    'He stirred amidst splintered wood and overturned barrels, a sickening pool of dried blood beneath him. His head throbbed, vision blurring through a haze of crimson. (Where... am I? This pain is unbearable. Who am I? I can''t remember anything at all.)',
    'A somber forest clearing, bathed in weak morning light, reveals the aftermath of an attack. Broken wooden barrels and scattered debris litter the weathered, blood-stained ground. Ancient trees loom silently overhead, their canopy filtering dim rays.',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/scene_m1_warrior.png',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/narration_m1_warrior.mp3',
    '[{"id": "choice_1", "text": "Try to stand up slowly and look around."}, {"id": "choice_2", "text": "Check my belongings to see what''s left."}, {"id": "choice_3", "text": "Listen carefully for any sounds or threats."}, {"id": "choice_4", "text": "Rest a moment and try to remember something."}]'::jsonb,
    TRUE,
    0
) ON CONFLICT (portrait_id, build_type) DO UPDATE SET
    narration = EXCLUDED.narration,
    visual_scene = EXCLUDED.visual_scene,
    image_url = EXCLUDED.image_url,
    audio_url = EXCLUDED.audio_url,
    choices = EXCLUDED.choices,
    is_successful = TRUE,
    retry_count = 0,
    last_error = NULL,
    generated_at = NOW();

INSERT INTO public.first_scenes (
    portrait_id, build_type, narration, visual_scene,
    image_url, audio_url, choices, is_successful, retry_count
) VALUES (
    'm2',
    'mage',
    'The world swam into blurry focus, a sharp pain pulsing behind his eyes. (Where am I? What happened? My head... everything hurts. I can''t remember anything.) Broken wood and spilled barrels lay nearby, dry blood clinging to his torn clothes. (Who am I?)',
    'A quiet forest clearing bathed in soft morning light. Broken wooden barrels and scattered debris lie strewn across the weathered, muddy ground, hinting at a recent struggle. Patches of dark, dry blood stain the earth.',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/scene_m2_mage.png',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/narration_m2_mage.mp3',
    '[{"id": "choice_1", "text": "Try to push myself up slowly and look around"}, {"id": "choice_2", "text": "Feel my pockets for any remaining belongings"}, {"id": "choice_3", "text": "Listen intently for any sounds or movement in the forest"}, {"id": "choice_4", "text": "Lie still for a moment, trying to recall even a single memory"}]'::jsonb,
    TRUE,
    0
) ON CONFLICT (portrait_id, build_type) DO UPDATE SET
    narration = EXCLUDED.narration,
    visual_scene = EXCLUDED.visual_scene,
    image_url = EXCLUDED.image_url,
    audio_url = EXCLUDED.audio_url,
    choices = EXCLUDED.choices,
    is_successful = TRUE,
    retry_count = 0,
    last_error = NULL,
    generated_at = NOW();

INSERT INTO public.first_scenes (
    portrait_id, build_type, narration, visual_scene,
    image_url, audio_url, choices, is_successful, retry_count
) VALUES (
    'm2',
    'ranger',
    'His head throbbed, vision swimming as he lay amidst shattered wood and robbed barrels, a dark stain near his face. (Where… am I? My head is splitting. I can''t remember anything at all. Who am I?) A dull ache spread through his weary limbs.',
    'A sun-dappled forest clearing shows scattered wooden debris and broken, empty barrels. Patches of dark, dry blood stain the weathered earth and torn fabric. Morning light filters through a canopy of tall, ancient trees.',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/scene_m2_ranger.png',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/narration_m2_ranger.mp3',
    '[{"id": "choice_1", "text": "Attempt to slowly sit up, bracing against the dizziness."}, {"id": "choice_2", "text": "Fumble weakly for any items remaining on my person."}, {"id": "choice_3", "text": "Strain to hear any sounds beyond my own throbbing pulse."}, {"id": "choice_4", "text": "Close my eyes for a moment, trying to clear the fog and remember anything."}]'::jsonb,
    TRUE,
    0
) ON CONFLICT (portrait_id, build_type) DO UPDATE SET
    narration = EXCLUDED.narration,
    visual_scene = EXCLUDED.visual_scene,
    image_url = EXCLUDED.image_url,
    audio_url = EXCLUDED.audio_url,
    choices = EXCLUDED.choices,
    is_successful = TRUE,
    retry_count = 0,
    last_error = NULL,
    generated_at = NOW();

INSERT INTO public.first_scenes (
    portrait_id, build_type, narration, visual_scene,
    image_url, audio_url, choices, is_successful, retry_count
) VALUES (
    'm2',
    'rogue',
    'He stirs amidst splintered wood and overturned barrels, a crimson stain beneath his head, vision blurring. The forest hums. (My head... it''s a throbbing drum. Where am I? What happened? I can''t remember anything.)',
    'A desolate forest clearing, broken wooden barrels and splintered debris litter the weathered ground. Soft morning light filters through ancient trees, illuminating dried bloodstains.',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/scene_m2_rogue.png',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/narration_m2_rogue.mp3',
    '[{"id": "choice_1", "text": "Try to push myself up slowly and scan my immediate surroundings"}, {"id": "choice_2", "text": "Pat down my clothes, checking for any items that might remain"}, {"id": "choice_3", "text": "Strain to hear anything beyond the forest sounds, any nearby threats"}, {"id": "choice_4", "text": "Lie still for another moment, trying to recall even a single memory"}]'::jsonb,
    TRUE,
    0
) ON CONFLICT (portrait_id, build_type) DO UPDATE SET
    narration = EXCLUDED.narration,
    visual_scene = EXCLUDED.visual_scene,
    image_url = EXCLUDED.image_url,
    audio_url = EXCLUDED.audio_url,
    choices = EXCLUDED.choices,
    is_successful = TRUE,
    retry_count = 0,
    last_error = NULL,
    generated_at = NOW();

INSERT INTO public.first_scenes (
    portrait_id, build_type, narration, visual_scene,
    image_url, audio_url, choices, is_successful, retry_count
) VALUES (
    'm2',
    'warrior',
    'A splitting pain throbbed behind his eyes as his blurry vision fought the dim forest light. (Where am I? This hurts... so much. Why can''t I remember anything?) Around him lay broken wood, scattered barrels, and dry blood. (What happened here? Who am I?)',
    'A muted forest clearing bathed in soft morning light. Broken wooden barrels and scattered debris litter the weathered, dirt-stained ground. Dried blood streaks a nearby patch, adding to the grim aftermath.',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/scene_m2_warrior.png',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/narration_m2_warrior.mp3',
    '[{"id": "choice_1", "text": "Try to push up slowly, testing my strength."}, {"id": "choice_2", "text": "Pat myself down, checking for injuries or belongings."}, {"id": "choice_3", "text": "Strain to hear anything beyond the ringing in my ears."}, {"id": "choice_4", "text": "Close my eyes for a moment, trying to recall *anything*."}]'::jsonb,
    TRUE,
    0
) ON CONFLICT (portrait_id, build_type) DO UPDATE SET
    narration = EXCLUDED.narration,
    visual_scene = EXCLUDED.visual_scene,
    image_url = EXCLUDED.image_url,
    audio_url = EXCLUDED.audio_url,
    choices = EXCLUDED.choices,
    is_successful = TRUE,
    retry_count = 0,
    last_error = NULL,
    generated_at = NOW();

INSERT INTO public.first_scenes (
    portrait_id, build_type, narration, visual_scene,
    image_url, audio_url, choices, is_successful, retry_count
) VALUES (
    'm3',
    'mage',
    'He stirred amidst shattered wood and upturned barrels, a sticky crimson patch beneath his head. Vision swam, his skull pounded. (Where am I? What happened? I can''t remember anything, and I feel so weak.)',
    'A dim forest clearing at dawn, dappled light filtering through tall pines. Broken wooden barrels and scattered debris litter the weathered, damp earth, stained with old blood.',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/scene_m3_mage.png',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/narration_m3_mage.mp3',
    '[{"id": "choice_1", "text": "Try to push myself up slowly and look around"}, {"id": "choice_2", "text": "Pat myself down to see if I have anything left"}, {"id": "choice_3", "text": "Listen carefully for any sounds beyond my own pulse"}, {"id": "choice_4", "text": "Lie still for a moment, trying to recall even a single memory"}]'::jsonb,
    TRUE,
    0
) ON CONFLICT (portrait_id, build_type) DO UPDATE SET
    narration = EXCLUDED.narration,
    visual_scene = EXCLUDED.visual_scene,
    image_url = EXCLUDED.image_url,
    audio_url = EXCLUDED.audio_url,
    choices = EXCLUDED.choices,
    is_successful = TRUE,
    retry_count = 0,
    last_error = NULL,
    generated_at = NOW();

INSERT INTO public.first_scenes (
    portrait_id, build_type, narration, visual_scene,
    image_url, audio_url, choices, is_successful, retry_count
) VALUES (
    'm3',
    'ranger',
    'He groaned, stirring on the weathered ground amidst shattered wood and robbed barrels, a dry pool of blood staining his clothes. His head pounded, vision swimming. (Everything hurts. Who am I? Where... where did I come from? I feel so weak, so lost.)',
    'A muted morning light filters through the canopy of a quiet forest clearing. Broken wooden barrels and other debris lie scattered across the weathered, muddy ground, hinting at a recent struggle. A dark stain marks the earth.',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/scene_m3_ranger.png',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/narration_m3_ranger.mp3',
    '[{"id": "choice_1", "text": "Try to stand up slowly and look around"}, {"id": "choice_2", "text": "Check my belongings to see what''s left"}, {"id": "choice_3", "text": "Listen carefully for any sounds or threats"}, {"id": "choice_4", "text": "Rest a moment and try to remember something"}]'::jsonb,
    TRUE,
    0
) ON CONFLICT (portrait_id, build_type) DO UPDATE SET
    narration = EXCLUDED.narration,
    visual_scene = EXCLUDED.visual_scene,
    image_url = EXCLUDED.image_url,
    audio_url = EXCLUDED.audio_url,
    choices = EXCLUDED.choices,
    is_successful = TRUE,
    retry_count = 0,
    last_error = NULL,
    generated_at = NOW();

INSERT INTO public.first_scenes (
    portrait_id, build_type, narration, visual_scene,
    image_url, audio_url, choices, is_successful, retry_count
) VALUES (
    'm3',
    'rogue',
    'He lay amidst splintered wood and overturned, robbed barrels, a dry blood pool beneath his head. (My head... what happened? I can''t see properly. Where am I? Nothing makes sense.)',
    'A dim forest clearing, shafts of morning light pierce the canopy, illuminating a chaotic mess of splintered wood and overturned, emptied barrels. The weathered earth is stained dark, a testament to recent violence. Twisted branches frame the scene.',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/scene_m3_rogue.png',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/narration_m3_rogue.mp3',
    '[{"id": "choice_1", "text": "Try to push myself up slowly and scan my surroundings."}, {"id": "choice_2", "text": "Pat myself down carefully, checking for any items or supplies."}, {"id": "choice_3", "text": "Close my eyes and listen intently for any nearby sounds."}, {"id": "choice_4", "text": "Lie still for a moment, trying to recall even a single memory."}]'::jsonb,
    TRUE,
    0
) ON CONFLICT (portrait_id, build_type) DO UPDATE SET
    narration = EXCLUDED.narration,
    visual_scene = EXCLUDED.visual_scene,
    image_url = EXCLUDED.image_url,
    audio_url = EXCLUDED.audio_url,
    choices = EXCLUDED.choices,
    is_successful = TRUE,
    retry_count = 0,
    last_error = NULL,
    generated_at = NOW();

INSERT INTO public.first_scenes (
    portrait_id, build_type, narration, visual_scene,
    image_url, audio_url, choices, is_successful, retry_count
) VALUES (
    'm3',
    'warrior',
    'The warrior stirs amidst scattered wood and plundered barrels, a dry pool of blood beneath him. His head throbs violently, vision swimming. (Where am I? Everything hurts, so much. I can''t remember anything, not even my name.) He feels incredibly weak, utterly disoriented.',
    'A quiet forest clearing bathed in soft morning light. Broken wooden barrels and scattered debris litter the weathered, dirt ground. Dry, dark blood stains the soil near some ripped cloth.',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/scene_m3_warrior.png',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/narration_m3_warrior.mp3',
    '[{"id": "choice_1", "text": "Try to stand up slowly and look around"}, {"id": "choice_2", "text": "Check my belongings to see what''s left"}, {"id": "choice_3", "text": "Listen carefully for any sounds or threats"}, {"id": "choice_4", "text": "Rest a moment and try to remember something"}]'::jsonb,
    TRUE,
    0
) ON CONFLICT (portrait_id, build_type) DO UPDATE SET
    narration = EXCLUDED.narration,
    visual_scene = EXCLUDED.visual_scene,
    image_url = EXCLUDED.image_url,
    audio_url = EXCLUDED.audio_url,
    choices = EXCLUDED.choices,
    is_successful = TRUE,
    retry_count = 0,
    last_error = NULL,
    generated_at = NOW();

INSERT INTO public.first_scenes (
    portrait_id, build_type, narration, visual_scene,
    image_url, audio_url, choices, is_successful, retry_count
) VALUES (
    'm4',
    'mage',
    'Splintered wood and overturned barrels lay scattered around him, a chill seeped from the dried blood beneath. His head pounded, vision swimming. (Where am I? Everything aches. I... I don''t remember anything. Who am I?)',
    'A somber forest clearing, strewn with broken wooden barrels and torn fabric. Faint morning light filters through ancient trees onto the damp, weathered ground. Dried blood darkens the scattered debris, hinting at recent violence.',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/scene_m4_mage.png',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/narration_m4_mage.mp3',
    '[{"id": "choice_1", "text": "Attempt to push myself up, slowly, despite the pain."}, {"id": "choice_2", "text": "Pat myself down, checking for any remaining items or supplies."}, {"id": "choice_3", "text": "Listen intently, trying to discern any sounds in the forest."}, {"id": "choice_4", "text": "Close my eyes, focusing on any scrap of memory that might return."}]'::jsonb,
    TRUE,
    0
) ON CONFLICT (portrait_id, build_type) DO UPDATE SET
    narration = EXCLUDED.narration,
    visual_scene = EXCLUDED.visual_scene,
    image_url = EXCLUDED.image_url,
    audio_url = EXCLUDED.audio_url,
    choices = EXCLUDED.choices,
    is_successful = TRUE,
    retry_count = 0,
    last_error = NULL,
    generated_at = NOW();

INSERT INTO public.first_scenes (
    portrait_id, build_type, narration, visual_scene,
    image_url, audio_url, choices, is_successful, retry_count
) VALUES (
    'm4',
    'ranger',
    'The figure lay amidst shattered wood and splintered barrels, a dark stain near his head. (My vision swims... everything hurts. I can''t recall a single thing before this pain. What is this place?)',
    'A somber forest clearing, bathed in weak morning light, reveals splintered wooden barrels and scattered debris. The weathered ground is stained dark, silent and still. Old, gnarled trees stand sentinel, their leaves rustling softly in the faint breeze.',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/scene_m4_ranger.png',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/narration_m4_ranger.mp3',
    '[{"id": "choice_1", "text": "Try to push myself up, just enough to clear my blurry vision."}, {"id": "choice_2", "text": "Pat my pockets and belt, see if I have anything left on me."}, {"id": "choice_3", "text": "Listen closely for any sounds that might indicate danger or help."}, {"id": "choice_4", "text": "Close my eyes for a moment, trying to force a memory to surface."}]'::jsonb,
    TRUE,
    0
) ON CONFLICT (portrait_id, build_type) DO UPDATE SET
    narration = EXCLUDED.narration,
    visual_scene = EXCLUDED.visual_scene,
    image_url = EXCLUDED.image_url,
    audio_url = EXCLUDED.audio_url,
    choices = EXCLUDED.choices,
    is_successful = TRUE,
    retry_count = 0,
    last_error = NULL,
    generated_at = NOW();

INSERT INTO public.first_scenes (
    portrait_id, build_type, narration, visual_scene,
    image_url, audio_url, choices, is_successful, retry_count
) VALUES (
    'm4',
    'rogue',
    'Pain lances through his skull as he blinks, vision blurring over shattered wood, overturned barrels, and a sticky patch of dry blood. (Where am I? What happened? I can''t remember anything, not even my name. Everything aches.)',
    'A tranquil, yet disturbed, forest clearing at dawn. Broken wooden barrels and splintered debris litter the damp, weathered ground, stained with dark, dry blood. Pale morning light filters through ancient trees.',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/scene_m4_rogue.png',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/narration_m4_rogue.mp3',
    '[{"id": "choice_1", "text": "Try to push myself up slowly, just to see what''s around me."}, {"id": "choice_2", "text": "Feel for any pouches or items left on my person."}, {"id": "choice_3", "text": "Strain to hear anything beyond my own ragged breathing."}, {"id": "choice_4", "text": "Close my eyes and try to force a memory, anything at all."}]'::jsonb,
    TRUE,
    0
) ON CONFLICT (portrait_id, build_type) DO UPDATE SET
    narration = EXCLUDED.narration,
    visual_scene = EXCLUDED.visual_scene,
    image_url = EXCLUDED.image_url,
    audio_url = EXCLUDED.audio_url,
    choices = EXCLUDED.choices,
    is_successful = TRUE,
    retry_count = 0,
    last_error = NULL,
    generated_at = NOW();

INSERT INTO public.first_scenes (
    portrait_id, build_type, narration, visual_scene,
    image_url, audio_url, choices, is_successful, retry_count
) VALUES (
    'm4',
    'warrior',
    'A heavy throbbing pain consumed his head as he lay amidst shattered wood and overturned barrels, his vision swimming through the haze. A patch of dried blood stained the ground nearby. (What... where am I? I can''t see properly. Nothing makes sense.)',
    'A quiet forest clearing bathed in soft morning light reveals a scene of disarray. Broken wooden barrels and scattered debris litter the weathered, dirt-trodden ground, hints of a past struggle amidst the ancient trees.',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/scene_m4_warrior.png',
    'http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes/narration_m4_warrior.mp3',
    '[{"id": "choice_1", "text": "Try to push myself up slowly, just to see if I can move."}, {"id": "choice_2", "text": "Pat down my clothes, checking if anything, anything at all, remains."}, {"id": "choice_3", "text": "Strain to listen beyond the ringing in my ears, for any nearby sounds."}, {"id": "choice_4", "text": "Close my eyes for a moment, wishing for a memory, any memory, to surface."}]'::jsonb,
    TRUE,
    0
) ON CONFLICT (portrait_id, build_type) DO UPDATE SET
    narration = EXCLUDED.narration,
    visual_scene = EXCLUDED.visual_scene,
    image_url = EXCLUDED.image_url,
    audio_url = EXCLUDED.audio_url,
    choices = EXCLUDED.choices,
    is_successful = TRUE,
    retry_count = 0,
    last_error = NULL,
    generated_at = NOW();

DO $$
DECLARE
    scene_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO scene_count FROM public.first_scenes WHERE is_successful = TRUE;
    RAISE NOTICE 'Total successful first scenes: %', scene_count;
    IF scene_count < 32 THEN
        RAISE WARNING 'Expected 32 first scenes but found %', scene_count;
    END IF;
END $$;
