#!/usr/bin/env python3
"""
Download all pre-generated first-scene assets (images + narration) and write
deterministic copies into supabase/character-images/first_scenes/, then emit
SQL INSERTs into supabase/seed_first_scenes.sql so `supabase db reset` (which
runs supabase/seed.sql) restores them with stable URLs.

Mirrors the lifecycle pattern used by save_builds_to_seed.py.

Run after `pregenerate_scenes.py` has populated the first_scenes table:
    cd backend && source venv/bin/activate
    python scripts/save_first_scenes_to_seed.py
"""

import json
import sys
from pathlib import Path

import httpx

sys.path.append(str(Path(__file__).parent.parent))

from services.supabase import supabase_service

REPO_ROOT = Path(__file__).parent.parent.parent
SEED_DIR = REPO_ROOT / "supabase" / "character-images" / "first_scenes"
SEED_SQL_PATH = REPO_ROOT / "supabase" / "seed_first_scenes.sql"
MAIN_SEED_PATH = REPO_ROOT / "supabase" / "seed.sql"
PUBLIC_BASE = "http://127.0.0.1:54331/storage/v1/object/public/character-images/first_scenes"
BLOCK_BEGIN = "-- BEGIN first_scenes seed (auto-managed by save_first_scenes_to_seed.py)"
BLOCK_END = "-- END first_scenes seed"


def _download(url: str, dest: Path) -> bool:
    try:
        r = httpx.get(url, timeout=30)
    except httpx.HTTPError as e:
        print(f"  ⚠️  download failed ({e}) for {url}")
        return False
    if r.status_code != 200:
        print(f"  ⚠️  HTTP {r.status_code} for {url}")
        return False
    dest.write_bytes(r.content)
    return True


def _sql_string(value: str) -> str:
    return value.replace("'", "''")


def save_first_scenes_to_seed() -> None:
    print("📦 Saving first scenes to seed directory...")
    SEED_DIR.mkdir(parents=True, exist_ok=True)

    result = (
        supabase_service.client.table("first_scenes")
        .select("*")
        .eq("is_successful", True)
        .order("portrait_id")
        .order("build_type")
        .execute()
    )
    scenes = result.data or []

    if not scenes:
        print("❌ No successful first scenes in DB. Run pregenerate_scenes.py first.")
        return

    print(f"✅ Found {len(scenes)} successful scenes")

    sql_lines = [
        "-- First scene seed data (auto-generated by save_first_scenes_to_seed.py)",
        "-- Restores pre-generated opening scenes for all portrait × build combos",
        "-- so gameplay starts instantly without waiting on Gemini/ElevenLabs.",
        "",
        "DELETE FROM public.first_scenes WHERE portrait_id ~ '^[mf][1-4]$';",
        "",
    ]

    saved = 0
    for scene in scenes:
        portrait_id = scene["portrait_id"]
        build_type = scene["build_type"]
        key = f"{portrait_id}_{build_type}"

        scene_image_dest = SEED_DIR / f"scene_{key}.png"
        narration_dest = SEED_DIR / f"narration_{key}.mp3"

        seeded_image_url: str | None = None
        seeded_audio_url: str | None = None

        if scene.get("image_url"):
            print(f"📥 {key}: image", end=" ")
            if _download(scene["image_url"], scene_image_dest):
                seeded_image_url = f"{PUBLIC_BASE}/scene_{key}.png"
                print("✅", end="")
            print()

        if scene.get("audio_url"):
            print(f"📥 {key}: audio", end=" ")
            if _download(scene["audio_url"], narration_dest):
                seeded_audio_url = f"{PUBLIC_BASE}/narration_{key}.mp3"
                print("✅", end="")
            print()

        narration_sql = _sql_string(scene["narration"])
        visual_sql = _sql_string(scene["visual_scene"])
        choices_sql = _sql_string(json.dumps(scene["choices"]))
        image_sql = f"'{seeded_image_url}'" if seeded_image_url else "NULL"
        audio_sql = f"'{seeded_audio_url}'" if seeded_audio_url else "NULL"

        sql_lines.append(
            f"""INSERT INTO public.first_scenes (
    portrait_id, build_type, narration, visual_scene,
    image_url, audio_url, choices, is_successful, retry_count
) VALUES (
    '{portrait_id}',
    '{build_type}',
    '{narration_sql}',
    '{visual_sql}',
    {image_sql},
    {audio_sql},
    '{choices_sql}'::jsonb,
    TRUE,
    0
) ON CONFLICT (portrait_id, build_type) DO UPDATE SET
    narration = EXCLUDED.narration,
    visual_scene = EXCLUDED.visual_scene,
    image_url = EXCLUDED.image_url,
    audio_url = EXCLUDED.audio_url,
    choices = EXCLUDED.choices,
    is_successful = TRUE,
    retry_count = 0,
    last_error = NULL,
    generated_at = NOW();"""
        )
        sql_lines.append("")
        saved += 1

    sql_lines.extend(
        [
            "DO $$",
            "DECLARE",
            "    scene_count INTEGER;",
            "BEGIN",
            "    SELECT COUNT(*) INTO scene_count FROM public.first_scenes WHERE is_successful = TRUE;",
            "    RAISE NOTICE 'Total successful first scenes: %', scene_count;",
            "    IF scene_count < 32 THEN",
            "        RAISE WARNING 'Expected 32 first scenes but found %', scene_count;",
            "    END IF;",
            "END $$;",
        ]
    )

    block = "\n".join(sql_lines) + "\n"
    SEED_SQL_PATH.write_text(block)
    print(f"\n💾 Wrote SQL → {SEED_SQL_PATH.relative_to(REPO_ROOT)}")

    # Splice the block into seed.sql between markers so `supabase db reset` picks it up.
    seed_text = MAIN_SEED_PATH.read_text() if MAIN_SEED_PATH.exists() else ""
    block_with_markers = f"\n{BLOCK_BEGIN}\n{block.rstrip()}\n{BLOCK_END}\n"
    if BLOCK_BEGIN in seed_text and BLOCK_END in seed_text:
        before = seed_text.split(BLOCK_BEGIN, 1)[0].rstrip() + "\n"
        after = seed_text.split(BLOCK_END, 1)[1].lstrip("\n")
        new_seed = before + block_with_markers + after
    else:
        new_seed = seed_text.rstrip() + "\n" + block_with_markers
    MAIN_SEED_PATH.write_text(new_seed)
    print(f"💾 Spliced into → {MAIN_SEED_PATH.relative_to(REPO_ROOT)}")
    print(f"💾 Wrote assets → {SEED_DIR.relative_to(REPO_ROOT)}/")
    print(f"📊 Seeded {saved}/{len(scenes)} scenes")


if __name__ == "__main__":
    save_first_scenes_to_seed()
